name: Close PR on README changes

on:
  pull_request:
    types: [edited]

jobs:
  close-pr:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Check for README.md changes
      run: |
        if git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep -q "README\.md"; then
          echo "::set-output name=close::true"
        else
          echo "::set-output name=close::false"
        fi
    - name: Close PR if README.md changed
      if: steps.check-for-readme-changes.outputs.close == 'true'
      uses: repo-sync/close-pull-request@v2
      with:
        message: 'This pull request has been closed because it modified the README.md file.'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
